name: Branch Tag
# run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:

jobs:
  tag-branch-name:
    name: tag branch name
    runs-on: ubuntu-latest
    steps:
      - name: checkout "${{ github.ref_name }}"
        uses: actions/checkout@v4
      
      
      - name: delete existing tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.ref_name }}",
            })

      - name: create tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.ref_name }}",
              sha: context.sha
            })